version: '3'
services:
    frontend:
        image: 7imbrook/sneak-speak:frontend
        ports:
            - 80:3000
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.edge==true
    backend:
        image: 7imbrook/sneak-speak:backend
        deploy:
            replicas: 1
        environment:
            - APIAI_TOKEN_FILE=/run/secrets/api_client_token
            - OPEN_WEATHER_MAP_API_KEY_FILEâ€˜=/run/secrets/weather_token
